### ISSUE TITLE
PersistentDictionary - Exception in .NET Core 2 application

### ISSUE THREAD

**Issue by kepboy** [microsoft/ManagedEsent#9]
I get the following exception when I try to create an instance of a PersistentDictionary in a .NET Core 2 console application.

"Type 'System.RuntimeType' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable."

The database is created though.

**Comment by michaelthorp** [comment]
I have not. My plan is to move ManagedEsent to .NET Core 2 but other work has come up and I haven't gotten to it yet.

**Comment by roicostas** [comment]
Same issue here, does this mean this library is not compatible with .NET Core 2? 
Is there a workaround to make it work with .NET Core 2?

**Comment by michaelthorp** [comment]
That is correct, we are planning for the next update to move it to .NET Core 2.

You could download the code and try re-targeting it yourself. I tried a while back and don't recall having any major issues, I just haven't had the time to get it tested properly so I haven't done the official move yet.

**Comment by bryanmcgrane** [comment]
I noticed this issue was closed, but am experience this issue after adding PersistentDictionary via Nuget. Is Nuget possibly behind master?

**Comment by michaelthorp** [comment]
Just wanted to post an update to this. We are slowly moving towards .NET Core/Standard. The current plan is for Esent.Interop and Isam to move to .NET Standard 2.0 (which can be used by .NET Framework and .NET Core apps) and EsentCollections to dual-release for .NET Framework and .NET Standard 2.1.

There are a few issues at the moment, related to types that are serializable in .NET Framework but not in .NET Core (this issue is one example of several) and we are working on fixing all of those before we release.

**Comment by michaelthorp** [comment]
All three packages are now .NET Standard 2.0 releases, as of version 2.0.0; so this should no longer be an issue.
